### ISSUE TITLE
RGB Related APIs Not Working

### ISSUE THREAD

**Issue by JerryZhangZZY** [srwi/qmk-via-api#1]
Hi! I am very interested in this project. I installed it using pip and tested some getters, such as `get_protocol_version()`, `get_layer_count()`, and `get_key()`, and they all worked properly, returning the correct information. However, when I used the RGB-related APIs, such as `get_color()` and `get_brightness()`, they returned **"None"**, and `set_color()` did not change the keyboard lighting. My keyboard can be modified normally in the VIA app for RGB settings. Do you know why these APIs are not working for me? My keyboard's protocol version is 12 btw.

**Comment by srwi** [comment]
Hi, were you able to resolve the issue yourself or why did you close it? Otherwise I can look into it soon. I honestly never tested the RGB related functions.

**Comment by JerryZhangZZY** [comment]
Hi there! I failed to resolved this issue as the core process is not in the Python layer. But I'm pretty sure that issue should be an error payload format. Actually, I started to build my own VIA API project this morning, which only focuses on the lighting function, and it works great. Here's the repo: [https://github.com/JerryZhangZZY/via-lighting-api](url). If you encounter any issues, I would be very happy to discuss with you.

**Comment by srwi** [comment]
Congrats on the project! Looks good and nicely documented!

I had a look at the problem again myself and fixed it in qmk-via-api as well now. I added the remaining missing led-related functions as well. Thanks for bringing it to my attention!
